name: flutter_bluetooth_app
description: A Flutter application for real-time communication via Bluetooth.
publish_to: 'none' 

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.0.0
  provider: ^6.0.0
  flutter_bluetooth_serial: ^0.4.0

# dependencies:

  # flutter:

    # sdk: flutter

  flutter_joystick: any


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true